# See https://sesamedisk.com/mysql-cluster-deploy-galera-with-mariadb-proxysql/
version: '3'
services:
  mariadb1:
    image: 'mariadb:10.7.3-focal'
    container_name: mariadb1
    ports:
      - '3306:3306'
    env_file: .env
    environment:
      - 'MARIADB_USER=${MARIADB_USER_1}'
      - 'MARIADB_PASSWORD=${MARIADB_PASSWORD_1}'
      - 'MARIADB_DATABASE=${MARIADB_DATABASE_1}'
      - 'MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
    volumes:
      - './mariadb1/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf'
      - './mariadb1/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    cap_add:
      - all
    networks:
      - mariadb
  mariadb2:
    image: 'mariadb:10.7.3-focal'
    container_name: mariadb2
    ports:
      - '3307:3306'
    env_file: .env
    environment:
      - 'MARIADB_USER=${MARIADB_USER_2}'
      - 'MARIADB_PASSWORD=${MARIADB_PASSWORD_2}'
      - 'MARIADB_DATABASE=${MARIADB_DATABASE_2}'
      - 'MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
    volumes:
      - './mariadb2/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf'
    cap_add:
      - all
    networks:
      - mariadb
  mariadb3:
    image: 'mariadb:10.7.3-focal'
    container_name: mariadb3
    ports:
      - '3308:3306'
    env_file: .env
    volumes:
      - './mariadb3/galera.cnf:/etc/mysql/mariadb.conf.d/galera.cnf'
    environment:
      - 'MARIADB_USER=${MARIADB_USER_3}'
      - 'MARIADB_PASSWORD=${MARIADB_PASSWORD_3}'
      - 'MARIADB_DATABASE=${MARIADB_DATABASE_3}'
      - 'MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}'
    cap_add:
      - all
    networks:
      - mariadb

  proxysql:
    image: 'proxysql/proxysql:latest'
    container_name: proxysql
    ports:
      - '6032:6032'
      - '6033:6033'
      - '6070:6070'
      - '6080:6080'
    cap_add:
      - all
    networks:
      - mariadb
    volumes:
      - './proxysql/proxysql.cnf:/etc/proxysql.cnf'
    command:
      - proxysql
      - '-f'
      - '--reload'
      - '-c'
      - /etc/proxysql.cnf
    depends_on:
      - mariadb1
      - mariadb2
      - mariadb3

networks:
  mariadb:
    driver: bridge
