version: '3'

services:
  mariadb-master:
    image: mariadb:10.7.3-focal
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - GALERA_NEW_CLUSTER=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --wsrep-new-cluster --wsrep-node-address='mariadb-master' --wsrep-cluster-address=gcomm://mariadb-master,mariadb-slave1,mariadb-slave2
    networks:
      - galera-network

  mariadb-slave1:
    image: mariadb:10.7.3-focal
    depends_on:
      - mariadb-master
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --wsrep-node-address='mariadb-slave1' --wsrep-cluster-address=gcomm://mariadb-master,mariadb-slave1,mariadb-slave2
    networks:
      - galera-network

  mariadb-slave2:
    image: mariadb:10.7.3-focal
    depends_on:
      - mariadb-master
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --wsrep-node-address='mariadb-slave2' --wsrep-cluster-address=gcomm://mariadb-master,mariadb-slave1,mariadb-slave2
    networks:
      - galera-network

#   proxysql1:
#     image: severalnines/proxysql
#     environment:
#       - CLUSTER_NAME=mycluster
#       - CLUSTER_JOIN=mariadb-master,mariadb-slave1,mariadb-slave2
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#     depends_on:
#       - mariadb-master
#       - mariadb-slave1
#       - mariadb-slave2
#     networks:
#       - galera-network
#
#   proxysql2:
#     image: severalnines/proxysql
#     environment:
#       - CLUSTER_NAME=mycluster
#       - CLUSTER_JOIN=mariadb-master,mariadb-slave1,mariadb-slave2
#       - MYSQL_ROOT_PASSWORD=password
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=password
#     depends_on:
#       - mariadb-master
#       - mariadb-slave1
#       - mariadb-slave2
#     networks:
#       - galera-network
#
networks:
  galera-network:
    driver: bridge
